# Generated by Django 5.0.2 on 2024-03-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='Sales',
        ),
        migrations.AlterField(
            model_name='sale',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Books', 'Books')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Cash', 'Cash'), ('Online Payment', 'Online Payment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shopping_mall',
            field=models.CharField(max_length=100),
        ),
    ]
