# Generated by Django 5.0.2 on 2024-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_remove_sale_sales_alter_sale_age_alter_sale_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.CharField(choices=[(0, 'Clothing'), (1, 'Electronics'), (2, 'Food'), (4, 'Books')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (0, 'Female')], max_length=55),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[(1, 'Credit Card'), (2, 'Debit Card'), (3, 'Cash'), (0, 'Online Payment')], max_length=50),
        ),
    ]
